using System.Text.Json.Nodes;
using Pokemanager.Model.Data;
using Pokemanager.Model.Edits;
using Pokemanager.Model.Projects;
using Pokemanager.Model.Resources;

namespace Pokemanager.Model.Editing;

/// <summary>
/// Editing state: the base data, the current data (base + edits) and the project where edits are recorded.
/// </summary>
/// <remarks>
/// Setting a value back to what the base had removes the edit instead of storing it, so the project only contains
/// real differences.
/// </remarks>
public sealed class EditorSession
{
    public Project Project { get; }

    /// <summary>Base romfs being edited: the randomizer output (if any) on top of the dump.</summary>
    public RomFsLayers Layers { get; }

    /// <summary>Base data (dump or randomized dump) without manual edits. Never modified.</summary>
    public GameData Original { get; }

    /// <summary>Data with the edits applied.</summary>
    public GameData Current { get; }

    public event EventHandler<EditKey>? Changed;

    private EditorSession(Project project, RomFsLayers layers, GameData original, GameData current)
    {
        Project = project;
        Layers = layers;
        Original = original;
        Current = current;
    }

    /// <summary>Loads the base twice (original and current) and applies the project edits.</summary>
    /// <param name="randomizedRomFs">romfs generated by the randomizer, layered over the dump. Null: no randomization.</param>
    /// <exception cref="InvalidDataException">An edit of the project does not fit the tables.</exception>
    public static EditorSession Open(Project project, string? randomizedRomFs = null)
    {
        var layers = randomizedRomFs is null
            ? new RomFsLayers(project.RomFsPath)
            : new RomFsLayers(randomizedRomFs, project.RomFsPath);
        var session = new EditorSession(project, layers, GameData.Load(layers), GameData.Load(layers));
        var errors = new List<string>();
        foreach (var edit in project.Edits.All)
        {
            try
            {
                GameTables.Get(edit.Table).Set(session.Current, edit.Id, edit.Field, edit.Value);
            }
            catch (Exception ex) when (ex is ArgumentException or InvalidOperationException or FormatException)
            {
                errors.Add($"{edit.Table}[{edit.Id}].{edit.Field}: {ex.Message}");
            }
        }

        if (errors.Count > 0)
            throw new InvalidDataException(Strings.Session_InvalidEdits + Environment.NewLine + string.Join(Environment.NewLine, errors));
        return session;
    }

    public JsonNode Get(string table, int id, string field) => GameTables.Get(table).Get(Current, id, field);

    public JsonNode GetOriginal(string table, int id, string field) => GameTables.Get(table).Get(Original, id, field);

    public int GetInt(string table, int id, string field) => Get(table, id, field).GetValue<int>();

    public void Set(string table, int id, string field, JsonNode value)
    {
        var def = GameTables.Get(table);
        var key = new EditKey(table, id, field);

        def.Set(Current, id, field, value);
        // Read back the applied value: it is normalized (e.g. learnset sorted, bytes truncated).
        JsonNode applied = def.Get(Current, id, field);

        if (JsonNode.DeepEquals(applied, def.Get(Original, id, field)))
            Project.Edits.Remove(key);
        else
            Project.Edits.Set(table, id, field, applied);

        Changed?.Invoke(this, key);
    }

    public void SetInt(string table, int id, string field, int value) => Set(table, id, field, JsonValue.Create(value));

    public bool IsModified(string table, int id, string field) => Project.Edits.Contains(new EditKey(table, id, field));

    public bool IsModified(string table, int id) => Project.Edits.Any(table, id);

    /// <summary>Undoes every edit of an entry.</summary>
    public void Revert(string table, int id)
    {
        var def = GameTables.Get(table);
        foreach (string field in def.Fields)
        {
            if (IsModified(table, id, field))
                Set(table, id, field, def.Get(Original, id, field));
        }
    }
}
