using System.Text.Json.Nodes;
using Pokemanager.Model.Data;
using Pokemanager.Model.Edits;
using Pokemanager.Model.Projects;
using Pokemanager.Model.Resources;

namespace Pokemanager.Model.Editing;

/// <summary>
/// Editing state: the base data, the current data (base + edits) and the project where edits are recorded.
/// </summary>
/// <remarks>
/// Setting a value back to what the base had removes the edit instead of storing it, so the project only contains
/// real differences.
/// </remarks>
public sealed class EditorSession
{
    public Project Project { get; }

    /// <summary>Base romfs being edited: the randomizer output (if any) on top of the dump.</summary>
    public RomFsLayers Layers { get; }

    /// <summary>Base data (dump or randomized dump) without manual edits. Never modified.</summary>
    public GameData Original { get; }

    /// <summary>Data with the edits applied.</summary>
    public GameData Current { get; }

    /// <summary>How many edits of the project said what the ROM already said, and were dropped when opening it.</summary>
    public int MatchedTheRom { get; private set; }

    public event EventHandler<EditKey>? Changed;

    private EditorSession(Project project, RomFsLayers layers, GameData original, GameData current)
    {
        Project = project;
        Layers = layers;
        Original = original;
        Current = current;
    }

    /// <summary>Loads the base twice (original and current) and applies the project edits.</summary>
    /// <param name="randomizedRomFs">romfs generated by the randomizer, layered over the dump. Null: no randomization.</param>
    /// <exception cref="InvalidDataException">An edit of the project does not fit the tables.</exception>
    public static EditorSession Open(Project project, string? randomizedRomFs = null)
    {
        var layers = randomizedRomFs is null
            ? new RomFsLayers(project.RomFsPath)
            : new RomFsLayers(randomizedRomFs, project.RomFsPath);
        var session = new EditorSession(project, layers, GameData.Load(layers, project.Game), GameData.Load(layers, project.Game));
        var errors = new List<string>();
        foreach (var edit in project.Edits.All.ToList())
        {
            var def = GameTables.Get(edit.Table);
            try
            {
                def.Set(session.Current, edit.Id, edit.Field, edit.Value);
            }
            catch (Exception ex) when (ex is ArgumentException or InvalidOperationException or FormatException
                                           or NullReferenceException or IndexOutOfRangeException or KeyNotFoundException)
            {
                errors.Add($"{edit.Table}[{edit.Id}].{edit.Field}: {ex.Message}");
                continue;
            }

            // An edit that writes what the ROM already says is not a change. They pile up when the base moves under
            // them — another seed, a rebuild, a data file imported from another ROM — and every entry then looked
            // "modified" although nothing of it differed. Same rule as Set: the project holds real differences only.
            if (JsonNode.DeepEquals(def.Get(session.Current, edit.Id, edit.Field), def.Get(session.Original, edit.Id, edit.Field)))
            {
                project.Edits.Remove(new EditKey(edit.Table, edit.Id, edit.Field));
                session.MatchedTheRom++;
            }
        }

        if (errors.Count > 0)
            throw new InvalidDataException(Strings.Session_InvalidEdits + Environment.NewLine + string.Join(Environment.NewLine, errors));
        return session;
    }

    public JsonNode Get(string table, int id, string field) => GameTables.Get(table).Get(Current, id, field);

    public JsonNode GetOriginal(string table, int id, string field) => GameTables.Get(table).Get(Original, id, field);

    public int GetInt(string table, int id, string field) => Get(table, id, field).GetValue<int>();

    public void Set(string table, int id, string field, JsonNode value)
    {
        var def = GameTables.Get(table);
        var key = new EditKey(table, id, field);

        def.Set(Current, id, field, value);
        // Read back the applied value: it is normalized (e.g. learnset sorted, bytes truncated).
        JsonNode applied = def.Get(Current, id, field);

        if (JsonNode.DeepEquals(applied, def.Get(Original, id, field)))
            Project.Edits.Remove(key);
        else
            Project.Edits.Set(table, id, field, applied);

        Changed?.Invoke(this, key);
    }

    public void SetInt(string table, int id, string field, int value) => Set(table, id, field, JsonValue.Create(value));

    public bool IsModified(string table, int id, string field) => Project.Edits.Contains(new EditKey(table, id, field));

    public bool IsModified(string table, int id) => Project.Edits.Any(table, id);

    /// <summary>The fields of an entry that differ from the ROM, so the marks can say what changed.</summary>
    public IReadOnlyList<string> ModifiedFields(string table, int id) =>
        [.. Project.Edits.All.Where(e => e.Table == table && e.Id == id).Select(e => e.Field)];

    /// <summary>Undoes every edit of the project, or only those of the tables <paramref name="table"/> accepts.</summary>
    public void RevertAll(Func<string, bool>? table = null)
    {
        foreach (var edit in Project.Edits.All.Where(e => table?.Invoke(e.Table) != false).ToList())
            SetBack(edit.Table, edit.Id, edit.Field);
    }

    /// <summary>Undoes every edit of an entry.</summary>
    public void Revert(string table, int id)
    {
        var def = GameTables.Get(table);
        foreach (string field in def.Fields)
        {
            if (IsModified(table, id, field))
                SetBack(table, id, field);
        }
    }

    /// <summary>Puts one field back to what the ROM says, and makes sure it stops counting as a change.</summary>
    private void SetBack(string table, int id, string field)
    {
        var def = GameTables.Get(table);
        Set(table, id, field, def.Get(Original, id, field));

        // A table that normalizes what it stores (a learnset comes back sorted) may not read back exactly what the ROM
        // has, and the edit would survive its own undo. The entry holds the ROM's data either way, so the mark goes.
        var key = new EditKey(table, id, field);
        if (Project.Edits.Remove(key))
            Changed?.Invoke(this, key);
    }
}
