<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Pokemanager.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pokemanager.Save\Pokemanager.Save.csproj" />
    <ProjectReference Include="..\Pokemanager.Battle\Pokemanager.Battle.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LiteNetLib" Version="2.1.4" />
  </ItemGroup>

</Project>
